name: Build Initial Report PDF
on:
  push:
    paths:
      - 'Initial-Report/**'
jobs:
  build_latex:
    runs-on: ubuntu-24.04
    steps:
      - uses: actions/checkout@v4
      - uses: xu-cheng/latex-action@v3
        with:
          root_file: main.tex
          working_directory: Initial-Report/
          latexmk_use_xelatex: true
      - uses: actions/upload-artifact@v4
        with:
          name: Initial-Report-PDF
          path: Initial-Report/main.pdf